# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Please do not edit this file. It is managed by puppet
# and any changes that you make will be overwritten the
# next time the puppet client runs on this system.
# 
# If you would like to make user specific settings,
# please put them in .profile
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


# include /etc/bash.bashrc if it exists
if [ -f "/etc/bash.bashrc" ]; then
  . "/etc/bash.bashrc"
fi

# vim:ft=sh
